apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      # port inside the cluster
      targetPort: 8888
      # port exposed outside the cluster
      # nodePort: 30000
